version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: repository-name
      POSTGRES_PASSWORD: repository-password
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
